import {
  developmentSchema,
  operationsDashboardSchema,
  operationsWorkspaceSchema,
  processDetailSchema,
  type Buyer,
  type Development,
  type OperationsDashboard,
  type OperationsWorkspace,
  type ProcessDetail,
  type ProcessDocument,
  type ProcessHistoryEvent,
  type ProcessNotification,
  type ProcessRequest,
  type ProcessRequirement,
  type ProcessSharedFile,
  type ProcessSubmission,
  type ProcessTask,
  type RegistrationProcess,
  type RegistrationSupplier,
} from "./registration-backoffice-schema";

function sleep(milliseconds: number): Promise<void> {
  return new Promise((resolve) => {
    setTimeout(resolve, milliseconds);
  });
}

const suppliers: RegistrationSupplier[] = [
  {
    id: "sup-1",
    name: "Construtora Prime",
    cnpj: "12345678000101",
    contactName: "Paula Menezes",
    contactEmail: "paula@prime.com.br",
    contactPhone: "(11) 99111-1101",
    status: "active",
    statusReason: null,
    developmentsCount: 2,
  },
  {
    id: "sup-2",
    name: "Banco Horizonte",
    cnpj: "98765432000188",
    contactName: "Ricardo Alves",
    contactEmail: "ricardo@horizonte.com.br",
    contactPhone: "(11) 99222-2202",
    status: "active",
    statusReason: null,
    developmentsCount: 1,
  },
  {
    id: "sup-3",
    name: "Incorporadora Atlas",
    cnpj: "11444777000165",
    contactName: "Marina Duarte",
    contactEmail: "marina@atlas.com.br",
    contactPhone: "(21) 99333-3303",
    status: "onboarding",
    statusReason: null,
    developmentsCount: 1,
  },
  {
    id: "supco_9b7c1d45-2f61-4d4f-8f26-1ef85f1137a1",
    name: "Atlas Incorporadora SPE Ltda",
    cnpj: "12345678000190",
    contactName: "Marina Duarte Soares",
    contactEmail: "marina.duarte@atlasresidencial.com.br",
    contactPhone: "(11) 99123-4567",
    status: "active",
    statusReason: null,
    developmentsCount: 1,
  },
];

const developments: Development[] = [
  {
    id: "dev-1",
    supplierId: "sup-1",
    name: "Residencial Aurora",
    cnpj: "12345678000101",
    address: "Av. Central, 1000 - Sao Paulo/SP",
    status: "active",
    buyersCount: 2,
  },
  {
    id: "dev-2",
    supplierId: "sup-1",
    name: "Parque das Aguas",
    cnpj: "12345678000101",
    address: "Rua das Palmeiras, 221 - Campinas/SP",
    status: "launching",
    buyersCount: 1,
  },
  {
    id: "dev-3",
    supplierId: "sup-2",
    name: "Jardins do Lago",
    cnpj: "98765432000188",
    address: "Alameda Azul, 88 - Curitiba/PR",
    status: "active",
    buyersCount: 1,
  },
  {
    id: "dev-4",
    supplierId: "sup-3",
    name: "Vista Sul Offices",
    cnpj: "11444777000165",
    address: "Av. Atlantica, 900 - Rio de Janeiro/RJ",
    status: "blocked",
    buyersCount: 1,
  },
  {
    id: "dev-atlas-1",
    supplierId: "supco_9b7c1d45-2f61-4d4f-8f26-1ef85f1137a1",
    name: "Atlas Residencial Fase 1",
    cnpj: "12345678000190",
    address: "Avenida Engenheiro Luis Carlos Berrini, 105 - Sao Paulo/SP",
    status: "active",
    buyersCount: 1,
  },
].map((item) => developmentSchema.parse(item));

const buyers: Buyer[] = [
  {
    id: "buy-1",
    supplierId: "sup-1",
    developmentId: "dev-1",
    name: "Marcos Silva",
    cpf: "12345678901",
    email: "marcos.silva@email.com",
    phone: "(11) 99888-0001",
    processId: "proc-1",
    status: "pending_documents",
    statusReason: null,
  },
  {
    id: "buy-2",
    supplierId: "sup-1",
    developmentId: "dev-1",
    name: "Juliana Rocha",
    cpf: "23456789012",
    email: "juliana.rocha@email.com",
    phone: "(11) 99888-0002",
    processId: "proc-2",
    status: "active",
    statusReason: null,
  },
  {
    id: "buy-3",
    supplierId: "sup-1",
    developmentId: "dev-2",
    name: "Felipe Nogueira",
    cpf: "34567890123",
    email: "felipe.n@email.com",
    phone: "(19) 99888-0003",
    processId: "proc-3",
    status: "active",
    statusReason: null,
  },
  {
    id: "buy-4",
    supplierId: "sup-2",
    developmentId: "dev-3",
    name: "Camila Freitas",
    cpf: "45678901234",
    email: "camila.f@email.com",
    phone: "(41) 99888-0004",
    processId: "proc-4",
    status: "active",
    statusReason: null,
  },
  {
    id: "buy-5",
    supplierId: "sup-3",
    developmentId: "dev-4",
    name: "Bruno Lima",
    cpf: "56789012345",
    email: "bruno.l@email.com",
    phone: "(21) 99888-0005",
    processId: "proc-5",
    status: "blocked",
    statusReason: "manual",
  },
  {
    id: "buy-atlas-1",
    supplierId: "supco_9b7c1d45-2f61-4d4f-8f26-1ef85f1137a1",
    developmentId: "dev-atlas-1",
    name: "Helena Martins",
    cpf: "67890123456",
    email: "helena.martins@email.com",
    phone: "(11) 99777-1122",
    processId: "proc-atlas-1",
    status: "active",
    statusReason: null,
  },
];

const processes: RegistrationProcess[] = [
  {
    id: "proc-1",
    supplierId: "sup-1",
    developmentId: "dev-1",
    buyerId: "buy-1",
    propertyLabel: "Apto 301 - Torre A",
    registrationNumber: "MAT-10001",
    registryOffice: "2o RGI Sao Paulo",
    internalOwner: "Camila Ribeiro",
    currentStep: "Bloco 1 - Certificado",
    status: "waiting_supplier",
    createdAt: "2026-02-05T12:00:00.000Z",
    dueAt: "2026-03-14T12:00:00.000Z",
    billing: {
      unitValue: 500,
      status: "pending",
      chargedAt: "2026-02-05T12:10:00.000Z",
      paidAt: null,
    },
    blocks: [
      {
        key: "certificate",
        title: "Certificado",
        status: "waiting_supplier",
        supplierActionRequired: true,
        validationOwner: "Time de documentação",
        documentsSummary: "RG, CPF e comprovante de endereço pendentes",
        latestResponseSummary: "Solicitação enviada e sem resposta do cliente",
        signatureLink: null,
        lastUpdatedAt: "2026-03-08T14:00:00.000Z",
        canStart: true,
        dependsOn: null,
      },
      {
        key: "contract",
        title: "Contrato",
        status: "pending",
        supplierActionRequired: false,
        validationOwner: "Jurídico",
        documentsSummary: "Aguardando liberação do bloco anterior",
        latestResponseSummary: "Não iniciado",
        signatureLink: null,
        lastUpdatedAt: "2026-03-08T14:00:00.000Z",
        canStart: false,
        dependsOn: "certificate",
      },
      {
        key: "registration",
        title: "Registro",
        status: "pending",
        supplierActionRequired: false,
        validationOwner: "Registro",
        documentsSummary: "Aguardando liberação do bloco anterior",
        latestResponseSummary: "Não iniciado",
        signatureLink: null,
        lastUpdatedAt: "2026-03-08T14:00:00.000Z",
        canStart: false,
        dependsOn: "contract",
      },
    ],
  },
  {
    id: "proc-2",
    supplierId: "sup-1",
    developmentId: "dev-1",
    buyerId: "buy-2",
    propertyLabel: "Apto 904 - Torre B",
    registrationNumber: "MAT-10002",
    registryOffice: "2º RGI São Paulo",
    internalOwner: "Mateus Leal",
    currentStep: "Bloco 2 - Contrato",
    status: "active",
    createdAt: "2026-01-20T09:00:00.000Z",
    dueAt: "2026-03-20T12:00:00.000Z",
    billing: {
      unitValue: 500,
      status: "paid",
      chargedAt: "2026-01-20T09:05:00.000Z",
      paidAt: "2026-01-25T13:00:00.000Z",
    },
    blocks: [
      {
        key: "certificate",
        title: "Certificado",
        status: "approved",
        supplierActionRequired: false,
        validationOwner: "Time de documentação",
        documentsSummary: "Certificado emitido",
        latestResponseSummary: "Documentos aprovados e certificado concluído",
        signatureLink: null,
        lastUpdatedAt: "2026-02-01T14:00:00.000Z",
        canStart: true,
        dependsOn: null,
      },
      {
        key: "contract",
        title: "Contrato",
        status: "waiting_signature",
        supplierActionRequired: true,
        validationOwner: "Jurídico",
        documentsSummary: "Escritura enviada para assinatura",
        latestResponseSummary: "Cliente precisa confirmar assinatura",
        signatureLink: "https://assinatura.parceira.com/contrato/proc-2",
        lastUpdatedAt: "2026-03-07T10:00:00.000Z",
        canStart: true,
        dependsOn: "certificate",
      },
      {
        key: "registration",
        title: "Registro",
        status: "pending",
        supplierActionRequired: false,
        validationOwner: "Registro",
        documentsSummary: "Aguardando contrato aprovado",
        latestResponseSummary: "Não iniciado",
        signatureLink: null,
        lastUpdatedAt: "2026-03-07T10:00:00.000Z",
        canStart: false,
        dependsOn: "contract",
      },
    ],
  },
  {
    id: "proc-atlas-1",
    supplierId: "supco_9b7c1d45-2f61-4d4f-8f26-1ef85f1137a1",
    developmentId: "dev-atlas-1",
    buyerId: "buy-atlas-1",
    propertyLabel: "Apto 1204 - Torre Atlas",
    registrationNumber: "MAT-30001",
    registryOffice: "4o RGI Sao Paulo",
    internalOwner: "Camila Ribeiro",
    currentStep: "Bloco 1 - Certificado",
    status: "active",
    createdAt: "2026-02-25T10:00:00.000Z",
    dueAt: "2026-03-30T12:00:00.000Z",
    billing: {
      unitValue: 500,
      status: "paid",
      chargedAt: "2026-02-25T10:05:00.000Z",
      paidAt: "2026-02-26T09:00:00.000Z",
    },
    blocks: [
      {
        key: "certificate",
        title: "Certificado",
        status: "approved",
        supplierActionRequired: false,
        validationOwner: "Time de documentação",
        documentsSummary: "Certificado concluído",
        latestResponseSummary: "Documentação aprovada pelo backoffice",
        signatureLink: null,
        lastUpdatedAt: "2026-03-01T10:30:00.000Z",
        canStart: true,
        dependsOn: null,
      },
      {
        key: "contract",
        title: "Contrato",
        status: "in_preparation",
        supplierActionRequired: false,
        validationOwner: "Jurídico",
        documentsSummary: "Minuta em preparação",
        latestResponseSummary: "Aguardando revisão interna",
        signatureLink: null,
        lastUpdatedAt: "2026-03-05T16:00:00.000Z",
        canStart: true,
        dependsOn: "certificate",
      },
      {
        key: "registration",
        title: "Registro",
        status: "pending",
        supplierActionRequired: false,
        validationOwner: "Registro",
        documentsSummary: "Aguardando conclusão do contrato",
        latestResponseSummary: "Não iniciado",
        signatureLink: null,
        lastUpdatedAt: "2026-03-05T16:00:00.000Z",
        canStart: false,
        dependsOn: "contract",
      },
    ],
  },
  {
    id: "proc-3",
    supplierId: "sup-1",
    developmentId: "dev-2",
    buyerId: "buy-3",
    propertyLabel: "Casa 14 - Quadra C",
    registrationNumber: "MAT-20001",
    registryOffice: "1º RGI Campinas",
    internalOwner: "Julia Martins",
    currentStep: "Bloco 3 - Registro",
    status: "requirement_open",
    createdAt: "2025-12-20T11:00:00.000Z",
    dueAt: "2026-03-01T12:00:00.000Z",
    billing: {
      unitValue: 500,
      status: "paid",
      chargedAt: "2025-12-20T11:05:00.000Z",
      paidAt: "2025-12-20T11:15:00.000Z",
    },
    blocks: [
      {
        key: "certificate",
        title: "Certificado",
        status: "approved",
        supplierActionRequired: false,
        validationOwner: "Time de documentação",
        documentsSummary: "Certificado emitido",
        latestResponseSummary: "Aprovado",
        signatureLink: null,
        lastUpdatedAt: "2026-01-02T14:00:00.000Z",
        canStart: true,
        dependsOn: null,
      },
      {
        key: "contract",
        title: "Contrato",
        status: "approved",
        supplierActionRequired: false,
        validationOwner: "Jurídico",
        documentsSummary: "Contrato assinado",
        latestResponseSummary: "Assinatura confirmada pelo cliente",
        signatureLink: "https://assinatura.parceira.com/contrato/proc-3",
        lastUpdatedAt: "2026-01-30T14:00:00.000Z",
        canStart: true,
        dependsOn: "certificate",
      },
      {
        key: "registration",
        title: "Registro",
        status: "requirement_open",
        supplierActionRequired: true,
        validationOwner: "Registro",
        documentsSummary: "Exigência do cartório aguardando saneamento",
        latestResponseSummary: "Cartório exigiu complemento do ITBI",
        signatureLink: null,
        lastUpdatedAt: "2026-03-05T09:00:00.000Z",
        canStart: true,
        dependsOn: "contract",
      },
    ],
  },
  {
    id: "proc-4",
    supplierId: "sup-2",
    developmentId: "dev-3",
    buyerId: "buy-4",
    propertyLabel: "Lote 08 - Jardim do Lago",
    registrationNumber: "MAT-30001",
    registryOffice: "3º RGI Curitiba",
    internalOwner: "Renata Castro",
    currentStep: "Cartório",
    status: "waiting_registry_office",
    createdAt: "2026-01-10T08:00:00.000Z",
    dueAt: "2026-04-05T12:00:00.000Z",
    billing: {
      unitValue: 500,
      status: "paid",
      chargedAt: "2026-01-10T08:10:00.000Z",
      paidAt: "2026-01-10T13:10:00.000Z",
    },
    blocks: [
      {
        key: "certificate",
        title: "Certificado",
        status: "approved",
        supplierActionRequired: false,
        validationOwner: "Time de documentação",
        documentsSummary: "Concluído",
        latestResponseSummary: "Concluído",
        signatureLink: null,
        lastUpdatedAt: "2026-01-15T10:00:00.000Z",
        canStart: true,
        dependsOn: null,
      },
      {
        key: "contract",
        title: "Contrato",
        status: "approved",
        supplierActionRequired: false,
        validationOwner: "Jurídico",
        documentsSummary: "Concluído",
        latestResponseSummary: "Concluído",
        signatureLink: "https://assinatura.parceira.com/contrato/proc-4",
        lastUpdatedAt: "2026-02-01T10:00:00.000Z",
        canStart: true,
        dependsOn: "certificate",
      },
      {
        key: "registration",
        title: "Registro",
        status: "waiting_registry_office",
        supplierActionRequired: false,
        validationOwner: "Registro",
        documentsSummary: "Documentos enviados ao cartório",
        latestResponseSummary: "Aguardando retorno do cartório",
        signatureLink: null,
        lastUpdatedAt: "2026-03-04T10:00:00.000Z",
        canStart: true,
        dependsOn: "contract",
      },
    ],
  },
  {
    id: "proc-5",
    supplierId: "sup-3",
    developmentId: "dev-4",
    buyerId: "buy-5",
    propertyLabel: "Sala 1201 - Vista Sul",
    registrationNumber: "MAT-40001",
    registryOffice: "5º RGI Rio",
    internalOwner: "Camila Ribeiro",
    currentStep: "Análise inicial",
    status: "overdue",
    createdAt: "2025-11-18T10:00:00.000Z",
    dueAt: "2026-02-25T12:00:00.000Z",
    billing: {
      unitValue: 500,
      status: "waived",
      chargedAt: null,
      paidAt: null,
    },
    blocks: [
      {
        key: "certificate",
        title: "Certificado",
        status: "rejected",
        supplierActionRequired: true,
        validationOwner: "Time de documentação",
        documentsSummary: "Comprovante de endereço divergente",
        latestResponseSummary: "Cliente precisa reenviar documentos",
        signatureLink: null,
        lastUpdatedAt: "2026-03-02T14:00:00.000Z",
        canStart: true,
        dependsOn: null,
      },
      {
        key: "contract",
        title: "Contrato",
        status: "pending",
        supplierActionRequired: false,
        validationOwner: "Jurídico",
        documentsSummary: "Bloqueado pelo bloco anterior",
        latestResponseSummary: "Não iniciado",
        signatureLink: null,
        lastUpdatedAt: "2026-03-02T14:00:00.000Z",
        canStart: false,
        dependsOn: "certificate",
      },
      {
        key: "registration",
        title: "Registro",
        status: "pending",
        supplierActionRequired: false,
        validationOwner: "Registro",
        documentsSummary: "Bloqueado pelo bloco anterior",
        latestResponseSummary: "Não iniciado",
        signatureLink: null,
        lastUpdatedAt: "2026-03-02T14:00:00.000Z",
        canStart: false,
        dependsOn: "contract",
      },
    ],
  },
];

const requests: ProcessRequest[] = [
  {
    id: "req-1",
    processId: "proc-1",
    block: "certificate",
    target: "buyer",
    title: "Enviar documentos pessoais do comprador",
    type: "document_submission",
    description: "Enviar RG, CPF e comprovante de endereço do comprador.",
    requiredDocuments: ["RG", "CPF", "Comprovante de endereço"],
    deadline: "2026-03-12T12:00:00.000Z",
    status: "sent",
    createdAt: "2026-03-08T13:45:00.000Z",
    sentAt: "2026-03-08T14:00:00.000Z",
    respondedAt: null,
  },
  {
    id: "req-2",
    processId: "proc-2",
    block: "contract",
    target: "supplier",
    title: "Confirmar assinatura do contrato",
    type: "signature",
    description: "Confirmar assinatura do contrato digital.",
    requiredDocuments: ["Contrato assinado"],
    deadline: "2026-03-11T18:00:00.000Z",
    status: "responded",
    createdAt: "2026-03-07T09:45:00.000Z",
    sentAt: "2026-03-07T10:00:00.000Z",
    respondedAt: "2026-03-09T11:00:00.000Z",
  },
  {
    id: "req-3",
    processId: "proc-3",
    block: "registration",
    target: "supplier",
    title: "Reenviar comprovante de ITBI",
    type: "correction",
    description: "Corrigir comprovante de ITBI apontado pelo cartório.",
    requiredDocuments: ["Comprovante ITBI atualizado"],
    deadline: "2026-03-13T18:00:00.000Z",
    status: "resubmission_requested",
    createdAt: "2026-03-05T08:45:00.000Z",
    sentAt: "2026-03-05T09:00:00.000Z",
    respondedAt: null,
  },
  {
    id: "req-4",
    processId: "proc-4",
    block: "registration",
    target: "supplier",
    title: "Confirmar pagamento da guia de ITBI",
    type: "payment",
    description: "Confirmar pagamento da guia de ITBI.",
    requiredDocuments: ["Comprovante de pagamento"],
    deadline: "2026-02-14T18:00:00.000Z",
    status: "completed",
    createdAt: "2026-02-10T08:45:00.000Z",
    sentAt: "2026-02-10T09:00:00.000Z",
    respondedAt: "2026-02-10T17:00:00.000Z",
  },
  {
    id: "req-5",
    processId: "proc-5",
    block: "certificate",
    target: "buyer",
    title: "Reenviar comprovante de endereço",
    type: "correction",
    description: "Reenviar comprovante de endereço com emissão inferior a 90 dias.",
    requiredDocuments: ["Comprovante de endereço atualizado"],
    deadline: "2026-03-04T12:00:00.000Z",
    status: "rejected",
    createdAt: "2026-03-01T08:45:00.000Z",
    sentAt: "2026-03-01T09:00:00.000Z",
    respondedAt: "2026-03-02T10:00:00.000Z",
  },
  {
    id: "req-6",
    processId: "proc-3",
    block: "registration",
    target: "supplier",
    title: "Novo envio do ITBI após reprovação",
    type: "document_submission",
    description: "Enviar nova versão do comprovante de ITBI com leitura legível.",
    requiredDocuments: ["Comprovante ITBI atualizado"],
    deadline: "2026-03-15T18:00:00.000Z",
    status: "in_review",
    createdAt: "2026-03-06T09:15:00.000Z",
    sentAt: "2026-03-06T09:30:00.000Z",
    respondedAt: "2026-03-07T16:20:00.000Z",
  },
];

const submissions: ProcessSubmission[] = [
  {
    id: "sub-1",
    requestId: "req-2",
    submittedBy: "supplier",
    submittedAt: "2026-03-09T11:00:00.000Z",
    notes: "Contrato assinado digitalmente e conferido pelo jurídico do cliente.",
  },
  {
    id: "sub-2",
    requestId: "req-5",
    submittedBy: "buyer",
    submittedAt: "2026-03-02T10:00:00.000Z",
    notes: "Comprador reenviou comprovante, mas o arquivo segue ilegível.",
  },
  {
    id: "sub-3",
    requestId: "req-6",
    submittedBy: "supplier",
    submittedAt: "2026-03-07T16:20:00.000Z",
    notes: "Nova via do ITBI anexada com todas as páginas e autenticação bancária.",
  },
];

const tasks: ProcessTask[] = [
  {
    id: "task-1",
    processId: "proc-1",
    title: "Cobrar cliente por documentos do certificado",
    description: "Fazer follow-up com Paula Menezes sobre pendência de RG e CPF.",
    assignee: "Camila Ribeiro",
    type: "follow_up",
    dueAt: "2026-03-11T16:00:00.000Z",
    status: "pending",
  },
  {
    id: "task-2",
    processId: "proc-2",
    title: "Validar assinatura eletrônica",
    description: "Conferir assinatura do contrato na plataforma de assinatura.",
    assignee: "Mateus Leal",
    type: "validation",
    dueAt: "2026-03-10T19:00:00.000Z",
    status: "in_progress",
  },
  {
    id: "task-3",
    processId: "proc-3",
    title: "Analisar exigência do cartório",
    description: "Verificar apontamento sobre ITBI e preparar resposta.",
    assignee: "Julia Martins",
    type: "analysis",
    dueAt: "2026-03-11T14:00:00.000Z",
    status: "pending",
  },
  {
    id: "task-4",
    processId: "proc-4",
    title: "Acompanhar cartório",
    description: "Solicitar previsão de conclusão para o cartório.",
    assignee: "Renata Castro",
    type: "contact",
    dueAt: "2026-03-12T10:00:00.000Z",
    status: "pending",
  },
  {
    id: "task-5",
    processId: "proc-5",
    title: "Reprovar comprovante",
    description: "Formalizar reprovação e solicitar reenvio ao cliente.",
    assignee: "Camila Ribeiro",
    type: "correction",
    dueAt: "2026-03-10T15:00:00.000Z",
    status: "completed",
  },
];

const documents: ProcessDocument[] = [
  {
    id: "doc-1",
    processId: "proc-1",
    requestId: "req-1",
    block: "certificate",
    type: "personal_documents",
    name: "Checklist comprador.pdf",
    fileUrl: "/mock-files/checklist-comprador.pdf",
    fileSize: 248_000,
    status: "sent",
    uploadedBy: "backoffice",
    version: 1,
    comments: "Checklist inicial anexado pelo backoffice para orientar o envio.",
    uploadedAt: "2026-03-08T14:00:00.000Z",
  },
  {
    id: "doc-2",
    processId: "proc-2",
    requestId: "req-2",
    block: "contract",
    type: "contract",
    name: "Contrato de compra e venda.pdf",
    fileUrl: "/mock-files/contrato-compra-venda-v1.pdf",
    fileSize: 1_420_000,
    status: "in_review",
    uploadedBy: "supplier",
    version: 1,
    comments: "Assinatura recebida e aguardando conferência final.",
    uploadedAt: "2026-03-09T11:00:00.000Z",
  },
  {
    id: "doc-3-v1",
    processId: "proc-3",
    requestId: "req-3",
    block: "registration",
    type: "itbi_receipt",
    name: "Comprovante ITBI.pdf",
    fileUrl: "/mock-files/itbi-v1.pdf",
    fileSize: 382_000,
    status: "rejected",
    uploadedBy: "supplier",
    version: 1,
    comments: "Arquivo cortado e sem autenticação legível.",
    uploadedAt: "2026-03-05T09:30:00.000Z",
  },
  {
    id: "doc-3-v2",
    processId: "proc-3",
    requestId: "req-6",
    block: "registration",
    type: "itbi_receipt",
    name: "Comprovante ITBI.pdf",
    fileUrl: "/mock-files/itbi-v2.pdf",
    fileSize: 466_000,
    status: "in_review",
    uploadedBy: "supplier",
    version: 2,
    comments: "Nova versão enviada após solicitação de reenvio.",
    uploadedAt: "2026-03-07T16:20:00.000Z",
  },
  {
    id: "doc-4",
    processId: "proc-4",
    requestId: "req-4",
    block: "registration",
    type: "deed",
    name: "Escritura final.pdf",
    fileUrl: "/mock-files/escritura-final.pdf",
    fileSize: 920_000,
    status: "approved",
    uploadedBy: "supplier",
    version: 1,
    comments: "Documento aprovado e pronto para protocolo em cartório.",
    uploadedAt: "2026-02-11T13:30:00.000Z",
  },
  {
    id: "doc-5-v1",
    processId: "proc-5",
    requestId: "req-5",
    block: "certificate",
    type: "personal_documents",
    name: "Comprovante endereço.png",
    fileUrl: "/mock-files/comprovante-endereco-v1.png",
    fileSize: 188_000,
    status: "rejected",
    uploadedBy: "buyer",
    version: 1,
    comments: "Imagem desfocada e sem data visível.",
    uploadedAt: "2026-03-02T10:00:00.000Z",
  },
  {
    id: "doc-5-v2",
    processId: "proc-5",
    requestId: "req-5",
    block: "certificate",
    type: "personal_documents",
    name: "Comprovante endereço.png",
    fileUrl: "/mock-files/comprovante-endereco-v2.png",
    fileSize: 202_000,
    status: "resubmission_requested",
    uploadedBy: "buyer",
    version: 2,
    comments: "Nova tentativa enviada; backoffice ainda solicitou reenquadramento.",
    uploadedAt: "2026-03-04T09:40:00.000Z",
  },
];

const requirements: ProcessRequirement[] = [
  {
    id: "reqm-1",
    processId: "proc-3",
    title: "Complementar ITBI",
    description: "Cartório exigiu comprovante atualizado de recolhimento do ITBI.",
    status: "in_resolution",
    supplierActionRequired: true,
    createdAt: "2026-03-05T09:00:00.000Z",
  },
  {
    id: "reqm-2",
    processId: "proc-4",
    title: "Confirmar reconhecimento de firma",
    description: "Exigência resolvida após validação cartorária.",
    status: "resolved",
    supplierActionRequired: false,
    createdAt: "2026-02-20T14:00:00.000Z",
  },
];

const history: ProcessHistoryEvent[] = [
  {
    id: "hist-1",
    processId: "proc-3",
    occurredAt: "2026-03-05T09:00:00.000Z",
    user: "Cartório 1º RGI Campinas",
    action: "Exigência aberta",
    note: "Solicitado comprovante atualizado do ITBI.",
    comment: null,
  },
  {
    id: "hist-2",
    processId: "proc-3",
    occurredAt: "2026-03-05T10:00:00.000Z",
    user: "Julia Martins",
    action: "Solicitação criada ao cliente",
    note: "Pedido de correção enviado com prazo de 48 horas.",
    comment: "Motivo informado: arquivo ilegível.",
  },
  {
    id: "hist-3",
    processId: "proc-2",
    occurredAt: "2026-03-09T11:00:00.000Z",
    user: "Cliente Construtora Prime",
    action: "Resposta do cliente",
    note: "Assinatura do contrato confirmada.",
    comment: "Submission registrada no portal do cliente.",
  },
  {
    id: "hist-4",
    processId: "proc-1",
    occurredAt: "2026-03-08T14:00:00.000Z",
    user: "Camila Ribeiro",
    action: "Solicitação criada",
    note: "Documentos do certificado solicitados ao cliente.",
    comment: null,
  },
  {
    id: "hist-5",
    processId: "proc-5",
    occurredAt: "2026-03-02T10:00:00.000Z",
    user: "Camila Ribeiro",
    action: "Documento reprovado",
    note: "Comprovante sem data válida para emissão do certificado.",
    comment: "Reenvio solicitado com prazo de 3 dias.",
  },
  {
    id: "hist-6",
    processId: "proc-3",
    occurredAt: "2026-03-07T16:20:00.000Z",
    user: "Cliente Construtora Prime",
    action: "Documento reenviado",
    note: "Comprovante de ITBI enviado na versão 2.",
    comment: "Documento vinculado à solicitação req-6.",
  },
  {
    id: "hist-7",
    processId: "proc-3",
    occurredAt: "2026-03-07T16:35:00.000Z",
    user: "Backoffice Registro360",
    action: "Documento em análise",
    note: "Backoffice iniciou validação da nova versão do ITBI.",
    comment: null,
  },
];

const notifications: ProcessNotification[] = [
  {
    id: "notif-1",
    processId: "proc-1",
    recipient: "buyer",
    title: "Nova solicitação criada",
    description: "Envio de documentos do certificado com prazo até 12/03.",
    createdAt: "2026-03-08T14:02:00.000Z",
  },
  {
    id: "notif-2",
    processId: "proc-3",
    recipient: "supplier",
    title: "Reenvio solicitado",
    description: "Comprovante de ITBI precisa ser reenviado com melhor legibilidade.",
    createdAt: "2026-03-05T10:00:00.000Z",
  },
  {
    id: "notif-3",
    processId: "proc-3",
    recipient: "backoffice",
    title: "Documento reenviado",
    description: "Nova versão do ITBI recebida e pronta para análise.",
    createdAt: "2026-03-07T16:21:00.000Z",
  },
  {
    id: "notif-4",
    processId: "proc-4",
    recipient: "supplier",
    title: "Documento aprovado",
    description: "Escritura final aprovada pelo backoffice.",
    createdAt: "2026-02-11T15:00:00.000Z",
  },
];

const sharedFiles: ProcessSharedFile[] = [
  {
    id: "shared-1",
    processId: "proc-2",
    block: "contract",
    audience: "supplier",
    title: "Minuta revisada do contrato",
    description: "Versão revisada pelo jurídico para conferência do supplier antes da assinatura final.",
    fileName: "minuta-contrato-v3.pdf",
    fileUrl: "/mock/shared/minuta-contrato-v3.pdf",
    uploadedBy: "Backoffice Registro360",
    createdAt: "2026-03-09T14:30:00.000Z",
  },
  {
    id: "shared-2",
    processId: "proc-3",
    block: "registration",
    audience: "buyer",
    title: "Guia de ITBI emitida",
    description: "Guia emitida para o comprador acompanhar o recolhimento no processo de registro.",
    fileName: "guia-itbi-proc-3.pdf",
    fileUrl: "/mock/shared/guia-itbi-proc-3.pdf",
    uploadedBy: "Backoffice Registro360",
    createdAt: "2026-03-05T10:00:00.000Z",
  },
  {
    id: "shared-3",
    processId: "proc-4",
    block: "registration",
    audience: "both",
    title: "Protocolo enviado ao cartório",
    description: "Comprovante do protocolo já encaminhado ao cartório, visível para supplier e comprador.",
    fileName: "protocolo-cartorio-proc-4.pdf",
    fileUrl: "/mock/shared/protocolo-cartorio-proc-4.pdf",
    uploadedBy: "Backoffice Registro360",
    createdAt: "2026-03-04T16:15:00.000Z",
  },
];

function getWorkspace(): OperationsWorkspace {
  return operationsWorkspaceSchema.parse({
    suppliers,
    developments,
    buyers,
    processes,
    requests,
    tasks,
    documents,
    requirements,
  });
}

function sortByDateDesc<T>(items: T[], accessor: (item: T) => string): T[] {
  return [...items].sort((left, right) => new Date(accessor(right)).getTime() - new Date(accessor(left)).getTime());
}

export async function fetchOperationsWorkspace(): Promise<OperationsWorkspace> {
  await sleep(180);
  return getWorkspace();
}

export async function fetchOperationsDashboard(): Promise<OperationsDashboard> {
  await sleep(180);
  const workspace = getWorkspace();
  const dashboard = {
    activeProcesses: workspace.processes.filter((item) => item.status === "active").length,
    waitingSupplier: workspace.processes.filter((item) => item.status === "waiting_supplier").length,
    waitingRegistryOffice: workspace.processes.filter((item) => item.status === "waiting_registry_office").length,
    processesWithRequirement: workspace.processes.filter((item) => item.status === "requirement_open").length,
    overdueProcesses: workspace.processes.filter((item) => item.status === "overdue").length,
    pendingTasks: workspace.tasks.filter((item) => item.status !== "completed" && item.status !== "cancelled").length,
    documentsWaitingValidation: workspace.documents.filter((item) => item.status === "in_review").length,
    criticalProcesses: workspace.processes.filter((item) => item.status === "overdue" || item.status === "requirement_open"),
    pendingRequests: workspace.requests.filter((item) =>
      ["created", "sent", "in_review", "resubmission_requested"].includes(item.status),
    ),
    recentlyCreatedProcesses: sortByDateDesc(workspace.processes, (item) => item.createdAt).slice(0, 3),
  };

  return operationsDashboardSchema.parse(dashboard);
}

export async function fetchProcessDetail(processId: string): Promise<ProcessDetail> {
  await sleep(120);
  const workspace = getWorkspace();
  const process = workspace.processes.find((item) => item.id === processId);

  if (!process) {
    throw new Error("Processo não encontrado.");
  }

  const supplier = workspace.suppliers.find((item) => item.id === process.supplierId);
  const development = workspace.developments.find((item) => item.id === process.developmentId);
  const buyer = workspace.buyers.find((item) => item.id === process.buyerId);

  if (!supplier || !development || !buyer) {
    throw new Error("Dados do processo estão inconsistentes.");
  }

  return processDetailSchema.parse({
    process,
    supplier,
    development,
    buyer,
    requests: requests.filter((item) => item.processId === processId),
    submissions: submissions.filter((item) =>
      requests.some((request) => request.processId === processId && request.id === item.requestId),
    ),
    tasks: tasks.filter((item) => item.processId === processId),
    documents: documents.filter((item) => item.processId === processId),
    requirements: requirements.filter((item) => item.processId === processId),
    notifications: notifications.filter((item) => item.processId === processId),
    sharedFiles: sharedFiles.filter((item) => item.processId === processId),
    history: sortByDateDesc(
      history.filter((item) => item.processId === processId),
      (item) => item.occurredAt,
    ),
  });
}
