export const routes = {
  login: "/login",
  dashboard: "/dashboard",
  suppliers: "/suppliers",
  supplierDetail: "/suppliers/:supplierId",
  supplierDetailById: (supplierId: string) => `/suppliers/${encodeURIComponent(supplierId)}`,
  developments: "/developments",
  developmentRegistration: "/developments/new",
  developmentDetail: "/developments/:developmentId",
  developmentDetailById: (developmentId: string) => `/developments/${encodeURIComponent(developmentId)}`,
  buyers: "/buyers",
  buyerDetail: "/buyers/:buyerId",
  buyerDetailById: (buyerId: string) => `/buyers/${encodeURIComponent(buyerId)}`,
  customers: "/customers",
  customerDetail: "/customers/:customerId",
  customerDetailById: (customerId: string) => `/customers/${encodeURIComponent(customerId)}`,
  developmentBuyerRegistration: "/developments/:developmentId/buyers/new",
  developmentBuyerRegistrationById: (developmentId: string) =>
    `/developments/${encodeURIComponent(developmentId)}/buyers/new`,
  processes: "/processes",
  processDetail: "/processes/:processId",
  processDetailById: (processId: string) => `/processes/${encodeURIComponent(processId)}`,
  requests: "/requests",
  tasks: "/tasks",
  documents: "/documents",
  requirements: "/requirements",
  settings: "/settings",
  workflowList: "/workflow/list",
  workflowSteps: "/workflows/:workflowId/steps",
  workflowStepsById: (workflowId: string) => `/workflows/${encodeURIComponent(workflowId)}/steps`,
  workflowRules: "/workflows/:workflowId/steps/:stepId/rules",
  workflowRulesById: (workflowId: string, stepId: string) =>
    `/workflows/${encodeURIComponent(workflowId)}/steps/${encodeURIComponent(stepId)}/rules`,
  backofficeUsers: "/settings/users",
  profile: "/profile",
} as const;
